# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
