# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goog', '0004_duration_search_engine_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
